spring:
    application:
        name: spring-ai-flight
#    profiles:
#        active: local

    datasource:
        url: jdbc:mariadb://localhost:3306/watch_store
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MariaDBDialect

    mail:
        host: smtp.mailtrap.io
        port: 2525
        username: 08c668f74bf006
        password: f6ef8168040e35
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    ai:
        vectorstore:
            qdrant:
                host: 127.0.0.1
                port: 6334
                api-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.ApheJ12lWHcB0gY8QCEcHIBJb_05A2t2o9yNTWslJ3s"
                collection-name: products
                distance: COSINE
                dimension: 3072
                initialize-schema: true
                grpc:
                    enabled: true

groq:
    api:
        key: ${GROQ_API_KEY}
        base-url: https://api.groq.com/openai/v1
        model: llama-3.3-70b-versatile
        temperature: 0.7
        max-output-tokens: 1024

# VNPay Configuration
vnpay:
    tmn-code: ${VNPAY_TMN_CODE}
    hash-secret: ${VNPAY_HASH_SECRET}
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: ${VNPAY_RETURN_URL}
    version: 2.1.0
    command: pay
    order-type: other

# Logging debug để xem request gửi đi
logging:
    level:
        org.springframework.web.client: DEBUG
        org.springframework.http.client: DEBUG
        org.springframework.ai: DEBUG
        iuh.fit.se.backend.service.AiService: DEBUG
